version: '3'
services:
  backend:
    build: ./backend
    container_name: backend
    restart: always
    expose:
      - "3000"
    networks:
      - app-network

  nginx:
    image: nginx:alpine
    container_name: nginx
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/certbot.conf:/etc/nginx/certbot.conf
      - certbot-etc:/etc/letsencrypt
      - certbot-var:/var/www/certbot
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - backend
      - certbot
    networks:
      - app-network

  certbot:
    image: certbot/certbot
    container_name: certbot
    volumes:
      - certbot-etc:/etc/letsencrypt
      - certbot-var:/var/www/certbot
    entrypoint: "/bin/sh -c 'trap exit TERM; while :; do sleep 6h & wait $!; certbot renew; done'"

networks:
  app-network:
    driver: bridge

volumes:
  certbot-etc:
  certbot-var:
